import "./globals.css";
import Navbar from "@/components/nav";
import { Mid } from "@/components/mid";
import Midbar from "@/components/midBar";
import HowToStart from "@/components/start";
import Influencers from "@/components/Influencers";
import Faq from "@/components/faq";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <title>{metadata.title}</title>
      <meta name="description" content={metadata.description} />
        <link
          href="https://fonts.googleapis.com/css2?family=Urbanist:wght@100;400;700;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className="font-urbanist antialiased min-h-screen"
        style={{ backgroundColor: "#181818" }}
      >
        <div className="min-h-screen">
          {/* Navbar */}
          <div>
            <Navbar />
          </div>

          {/* Main content starts here */}
          <div className="md:mt-6 md:ml-[120px] sm:ml-4">
            <Mid />
          </div>

          <div className="md:mt-8 md:ml-[150px] sm:ml-4 min-h-screen">
            <Midbar />
          </div>

          <div className="md:mt-8 sm:mx-4">
            <Influencers />
          </div>

          <div className="mt-8 sm:mx-4">
            <HowToStart />
          </div>

          <div className=" ">
            <Faq />
          </div>
        </div>
      </body>
    </html>
  );
}
